run_config:
  output: "artifacts"
  s3_bucket: "cloud-raw"
  s3_key: "Data Science Salary 2021 to 2023.csv"

create_dataset:
  columns:
    - work_year
    - experience_level
    - employment_type
    - job_title
    - salary
    - salary_currency
    - salary_in_usd
    - company_location
    - company_size

aws:
  upload: True
  bucket_name: "cloud-result"


generate_features:
  job_title_categorization: True

train_model:
  parameters:
    GradientBoostingRegressor:
      - n_estimators: [100, 300]
        learning_rate: [0.1, 0.01, 0.2]
        max_depth: [3, 4, 5, 6]
        min_samples_leaf: [1, 3, 5]
    DecisionTreeRegressor:
      - max_depth: [3, 4, 5, 6]
        min_samples_split: [2, 5, 10]
        min_samples_leaf: [1, 2, 4]
    RandomForestRegressor:
      - n_estimators: [10, 50, 100, 200, 300, 400, 500, 600, 700, 800]
        max_depth: [3, 4, 5, 6]
        min_samples_split: [2, 5, 10]
        min_samples_leaf: [1, 2, 4]
    XGBRegressor:
      - colsample_bytree: [0.3, 0.7]
        learning_rate: [0.05, 0.2]
        max_depth: [3, 5, 7]
        alpha: [5, 10]
        n_estimators: [50, 100, 200]
  train_test_split:
    test_size: 0.2
    random_state: 42
