aws:
  bucket_name: cloud-result
  upload: true
create_dataset:
  columns:
  - work_year
  - experience_level
  - employment_type
  - job_title
  - salary
  - salary_currency
  - salary_in_usd
  - company_location
  - company_size
generate_features:
  job_title_categorization: true
run_config:
  output: artifacts
  s3_bucket: cloud-raw
  s3_key: Data Science Salary 2021 to 2023.csv
train_model:
  parameters:
    DecisionTreeRegressor:
    - max_depth:
      - 3
      - 4
      - 5
      - 6
      min_samples_leaf:
      - 1
      - 2
      - 4
      min_samples_split:
      - 2
      - 5
      - 10
    GradientBoostingRegressor:
    - learning_rate:
      - 0.1
      - 0.01
      - 0.2
      max_depth:
      - 3
      - 4
      - 5
      - 6
      min_samples_leaf:
      - 1
      - 3
      - 5
      n_estimators:
      - 100
      - 300
    RandomForestRegressor:
    - max_depth:
      - 3
      - 4
      - 5
      - 6
      min_samples_leaf:
      - 1
      - 2
      - 4
      min_samples_split:
      - 2
      - 5
      - 10
      n_estimators:
      - 10
      - 50
      - 100
      - 200
      - 300
      - 400
      - 500
      - 600
      - 700
      - 800
    XGBRegressor:
    - alpha:
      - 5
      - 10
      colsample_bytree:
      - 0.3
      - 0.7
      learning_rate:
      - 0.05
      - 0.2
      max_depth:
      - 3
      - 5
      - 7
      n_estimators:
      - 50
      - 100
      - 200
  train_test_split:
    random_state: 42
    test_size: 0.2
