data:
  file: artifacts/features.csv
models:
  files:
  - XGBRegressor_model.pkl
  - GradientBoostingRegressor_model.pkl
  - DecisionTreeRegressor_model.pkl
  path: artifacts
s3_buckets:
  config_bucket: cloud-result
  data_bucket: cloud-result
  model_bucket: cloud-result
